name: Deploy Hello World App
run-name: Deploy Hello World App
on:
  workflow_run:
    workflows: ["Provision K3s"]
    types:
      - completed
  workflow_dispatch: 
jobs:
  Deploy_App:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Install Helm
        uses: azure/setup-helm@v3
      - name: Save decoded kube config
        run: |
          echo "${{ secrets.BASE64_KUBE_CONFIG }}" > ./.base64.kube.config
          mkdir $HOME/.kube
          base64 -d ./.base64.kube.config > $HOME/.kube/config
      - name: Helm Build Dependencies
        run: helm dependency build
        working-directory: ./.helm
      - name: Helm Deploy
        # Skip TLS verification because we are using a self-signed certificate
        # Install Cert manager only if we are using HTTPS
        run: |
          helm install --insecure-skip-tls-verify hello-world --wait \
          --set-file "index_file=index.html" \
          --set is_https=${{ secrets.IS_HTTPS }} \
          --set cert-manager.enabled=${{ secrets.IS_HTTPS }} \
          --set email="${{ secrets.EMAIL }}" \
          --set domain="${{ secrets.DOMAIN }}" \
          --set is_prod=${{ secrets.IS_PROD }} \
          ./.helm/