name: Deploy Hello World App
run-name: Deploy Hello World App
on:
  workflow_run:
    workflows: ["Provision K3s"]
    types:
      - completed
  workflow_dispatch: 
jobs:
  Deploy_App:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Install kubectl
        uses: azure/setup-kubectl@v3
        id: install
      - name: Save decoded kube config
        run: |
          echo "${{ secrets.BASE64_KUBE_CONFIG }}" > ./.base64.kube.config
          mkdir $HOME/.kube
          base64 -d ./.base64.kube.config > $HOME/.kube/config
      - name: Create config map
        # Ignore TLS because of self-signed certificate
        run: |
          kubectl create configmap hello-world --from-file index.html -o yaml --dry-run=client --insecure-skip-tls-verify > configMap.yml
          kubectl apply -f configMap.yml --insecure-skip-tls-verify
      - name: Create app
        # Ignore TLS because of self-signed certificate
        run: kubectl apply -f ./.kubernetes/hello-world.yml --insecure-skip-tls-verify